---
- name: "Run general setup"
  ansible.builtin.import_tasks: "setup.yml"
  tags:
    - "zwavejsui"
    - "zwave-js-ui"
    - "zwavejsui:setup"

- name: "Run network setup"
  ansible.builtin.import_tasks: "network.yml"
  tags:
    - "zwavejsui"
    - "zwave-js-ui"
    - "zwavejsui:network"
  when: "zwavejsui_docker_network_create"

- name: "Create container"
  ansible.builtin.import_tasks: "container.yml"
  tags:
    - "zwavejsui"
    - "zwave-js-ui"
    - "zwavejsui:docker"
