---
- name: "Create Docker network"
  community.docker.docker_network:
    name: "{{ zwavejsui_docker_network }}"
    driver: "{{ zwavejsui_docker_network_driver }}"
    enable_ipv6: "{{ zwavejsui_docker_network_enable_ipv6 }}"
    internal: "{{ zwavejsui_docker_network_internal }}"
    scope: "{{ zwavejsui_docker_network_scope }}"
    ipam_config:
      - subnet: "{{ zwavejsui_docker_network_subnet }}"
        gateway: "{{ zwavejsui_docker_network_gateway }}"
  when: "zwavejsui_docker_network_create"
