---
- name: "Create zwave-js-ui data directory"
  ansible.builtin.file:
    name: "{{ zwavejsui_docker_data_dir }}"
    state: "directory"
    mode: "0770"
  when: "not zwavejsui_docker_use_volumes"

- name: "Create zwave-js-ui Docker volume"
  community.docker.docker_volume:
    name: "{{ zwavejsui_docker_volume_name }}"
  when: "zwavejsui_docker_use_volumes"
